version: '3.6'

services:
  my-app-api:
    container_name: todo_server
    build: ./ # points to the dockerfile in the main directory
    command: npm start
    working_dir: /usr/src/docker-test
    environment:
      MONGODB_URI: 'mongodb://mongodb/TodoDB'
    ports:
      - "9000:9000"
    volumes:
      - ./:/usr/src/docker-test
    links:
      - mongodb

  mongodb:
    container_name: todo_mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
